apiVersion: v1
kind: Service
metadata:
  name: wp-svc
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - port: 5050
    name: http
    protocol: TCP
    targetPort: 5050

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deploy
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: my-wp
          imagePullPolicy: Never
          ports:
            - containerPort: 5050

