apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  labels:
    app: grafana
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.104
  selector:
    app: grafana
  ports:
  - port: 3000
    name: http
    protocol: TCP
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana-img
        imagePullPolicy: Never
        ports:
          - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: admin
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin
        - name: INFLUX_USER
          value: admin
        - name: INFLUX_URL
          value: "http://influxdb-svc:8086"
        - name: INFLUX_PASSWORD
          value: "admin"
