apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-image
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 10100
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.105
  selector:
    app: ftps
  ports:
  - port: 21
    name: ftp-http
    targetPort: 21
  - port: 10100
    name: ftp-passv
    targetPort: 10100
  - port: 20
    name: ftp-data
    targetPort: 20
