apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.103
  selector:
    app: phpmyadmin
  ports:
  - port: 5000
    name: http
    protocol: TCP
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deploy
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin-img
        imagePullPolicy: Never
        ports:
        - containerPort: 5000

