apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-vc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  selector:
    app: ftps
  ports:
  - port: 21
    name: ftps-http
    protocol: TCP
    targetPort: 21
  - port: 10100
    name: ftps-passv
    protocol: TCP
    targetPort: 10100
  - port: 20
    name: ftps-data
    protocol: TCP
    targetPort: 20
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deploy
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-img
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftps-http
        - containerPort: 10100
          name: ftps-passv
        - containerPort: 20
          name: ftps-data
        volumeMounts:
        - name: ftps-storage
          mountPath: /var/ftp
      volumes:
        - name: ftps-storage
          persistentVolumeClaim:
            claimName: ftps-vc
